// Generated by CoffeeScript 1.12.6
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.use("/:filename", function(req, res) {
    return res.sendFile(req.params.filename, {
      root: "./",
      acceptRanges: true
    });
  });

  app.listen(5656);

}).call(this);
